import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';
import{detectFrame,prepareVision,type VisionFrame,type VisionMode}from'./vision';
import{estimateStoredBytes,listFrameMeta,saveFrame,saveProject,testIndexedDb}from'./storage';
import{ManualPeer,deviceId as makeDeviceId,makeSessionCode,type DeviceRole}from'./multidevice';
import{angularDistance,downloadBlob,makeObjectMask,meshToGlb,meshToObj,meshToPly,reconstructVisualHull,type ObjectBox,type ObjectKeyframe,type ReconMesh}from'./reconstruction';
import{MeshPreview}from'./preview3d';

type Mode='object'|'room'|'human'|'mocap';
type HumanProfile='head'|'upper'|'full'|'face';
const POSE_CONNECTIONS=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28],[27,29],[29,31],[28,30],[30,32]];
const HAND_CONNECTIONS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
const sectorNames=['Trước','Trước-phải','Phải','Sau-phải','Sau','Sau-trái','Trái','Trước-trái'];
const modes:{id:Mode;title:string;sub:string;icon:string}[]=[
 {id:'object',title:'Vật thể 3D',sub:'Quay liên tục → mesh thật',icon:'⬡'},
 {id:'room',title:'Phòng / hiện trạng',sub:'Camera + coverage + đo chuẩn',icon:'⌂'},
 {id:'human',title:'Người / Avatar',sub:'Mặt, nửa người hoặc toàn thân',icon:'♙'},
 {id:'mocap',title:'Motion Capture',sub:'Pose + mặt + bàn tay',icon:'◎'}
];

function App(){
 const videoRef=useRef<HTMLVideoElement>(null),overlayRef=useRef<HTMLCanvasElement>(null),previewRef=useRef<HTMLCanvasElement>(null),streamRef=useRef<MediaStream|null>(null),rafRef=useRef(0),lastDetectRef=useRef(0),lastVisionRef=useRef<VisionFrame>({}),previewEngineRef=useRef<MeshPreview|null>(null);
 const [mode,setMode]=useState<Mode>('object'),modeRef=useRef<Mode>('object');
 const [cameraOn,setCameraOn]=useState(false),[visionReady,setVisionReady]=useState(false),visionReadyRef=useRef(false),[message,setMessage]=useState('Bật camera và đặt vật thể vào giữa khung.');
 const [devices,setDevices]=useState<MediaDeviceInfo[]>([]),[deviceId,setDeviceId]=useState(''),[resolution,setResolution]=useState('1280x720'),[fps,setFps]=useState(0),[videoSize,setVideoSize]=useState('—');
 const [secure]=useState(window.isSecureContext),[webgl,setWebgl]=useState(false),[webgpu,setWebgpu]=useState(false),[webxr,setWebxr]=useState(false),[idbOk,setIdbOk]=useState(false);
 const [orientationEnabled,setOrientationEnabled]=useState(false),orientationRef=useRef<number|null>(null);
 const [objectLock,setObjectLock]=useState<ObjectBox|null>(null),objectLockRef=useRef<ObjectBox|null>(null),[objectLabel,setObjectLabel]=useState('Chưa khóa');
 const [continuous,setContinuous]=useState(false),continuousRef=useRef(false),captureBusyRef=useRef(false),lastCaptureTsRef=useRef(0),lastAngleRef=useRef<number|null>(null);
 const [keyframes,setKeyframes]=useState<ObjectKeyframe[]>([]),keyframesRef=useRef<ObjectKeyframe[]>([]),[coverage,setCoverage]=useState<boolean[]>(Array(8).fill(false)),coverageRef=useRef<boolean[]>(Array(8).fill(false));
 const [scanQuality,setScanQuality]=useState({brightness:0,sharpness:0,tracking:0,mask:0}),[widthMm,setWidthMm]=useState('300'),[voxelRes,setVoxelRes]=useState(42),[mesh,setMesh]=useState<ReconMesh|null>(null),[building,setBuilding]=useState(false);
 const [humanProfile,setHumanProfile]=useState<HumanProfile>('upper'),humanProfileRef=useRef<HumanProfile>('upper'),[humanRegions,setHumanRegions]=useState({face:0,torso:0,leftArm:0,rightArm:0,legs:0,hands:0});
 const [storedFrames,setStoredFrames]=useState(0),[storedBytes,setStoredBytes]=useState(0),[humanAuto,setHumanAuto]=useState(false),humanAutoRef=useRef(false),[humanKeyframes,setHumanKeyframes]=useState(0),humanCaptureBusyRef=useRef(false),humanLastTsRef=useRef(0),humanLastAngleRef=useRef<number|null>(null);
 const [multiOpen,setMultiOpen]=useState(false),peerRef=useRef<ManualPeer|null>(null),[peerState,setPeerState]=useState('Chưa kết nối'),[signalIn,setSignalIn]=useState(''),[signalOut,setSignalOut]=useState(''),[role,setRole]=useState<DeviceRole>('auto'),[sessionCode]=useState(makeSessionCode());
 const localDeviceId=useRef(makeDeviceId()),projectId=useRef(globalThis.crypto?.randomUUID?.()??`project-${Date.now()}`),createdAt=useRef(new Date().toISOString());

 useEffect(()=>{modeRef.current=mode;if(cameraOn){stopCamera(false);void startCamera()}setObjectLock(null);objectLockRef.current=null;setContinuous(false);continuousRef.current=false;setMesh(null);},[mode]);
 useEffect(()=>{visionReadyRef.current=visionReady},[visionReady]);
 useEffect(()=>{continuousRef.current=continuous},[continuous]);
 useEffect(()=>{objectLockRef.current=objectLock},[objectLock]);
 useEffect(()=>{keyframesRef.current=keyframes},[keyframes]);
 useEffect(()=>{coverageRef.current=coverage},[coverage]);
 useEffect(()=>{humanProfileRef.current=humanProfile},[humanProfile]);
 useEffect(()=>{humanAutoRef.current=humanAuto},[humanAuto]);
 useEffect(()=>{const c=document.createElement('canvas');setWebgl(!!(c.getContext('webgl2')||c.getContext('webgl')));setWebgpu('gpu'in navigator);setWebxr('xr'in navigator);void testIndexedDb().then(setIdbOk);return()=>{stopCamera(false);peerRef.current?.close();previewEngineRef.current?.dispose();keyframesRef.current.forEach(k=>k.previewUrl&&URL.revokeObjectURL(k.previewUrl))}},[]);
 useEffect(()=>{if(!previewRef.current)return;previewEngineRef.current?.dispose();previewEngineRef.current=new MeshPreview(previewRef.current);return()=>previewEngineRef.current?.dispose()},[]);
 useEffect(()=>{if(mesh)previewEngineRef.current?.setMesh(mesh)},[mesh]);

 async function enumerate(){try{setDevices((await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput'))}catch{setDevices([])}}
 async function startCamera(forcedId?:string){
  if(!navigator.mediaDevices?.getUserMedia){setMessage('Trình duyệt không hỗ trợ camera web.');return}stopCamera(false);setMessage('Đang mở camera…');
  try{const[w,h]=resolution.split('x').map(Number);const id=forcedId??deviceId;const s=await navigator.mediaDevices.getUserMedia({video:id?{deviceId:{exact:id},width:{ideal:w},height:{ideal:h}}:{facingMode:{ideal:'environment'},width:{ideal:w},height:{ideal:h}},audio:false});streamRef.current=s;const v=videoRef.current!;v.srcObject=s;await v.play();setCameraOn(true);setVideoSize(`${v.videoWidth}×${v.videoHeight}`);await enumerate();const actual=s.getVideoTracks()[0]?.getSettings().deviceId;if(actual&&!deviceId)setDeviceId(actual);
   if(modeRef.current!=='room'){setMessage('Đang tải nhận diện AI…');try{await prepareVision(modeRef.current as VisionMode);setVisionReady(true);if(modeRef.current==='object')setMessage('Camera sẵn sàng. Khóa vật thể rồi bấm Quét liên tục.');else setMessage('Tracking sẵn sàng. Chọn phạm vi người cần quét.')}catch(e){console.error(e);setVisionReady(false);setMessage('Camera chạy nhưng AI chưa tải được. Kiểm tra mạng rồi thử lại.')}}else setMessage('Camera sẵn sàng cho quét hiện trạng.');
   loop();
  }catch(e){console.error(e);setCameraOn(false);setMessage('Không mở được camera. Hãy cấp quyền và dùng HTTPS/localhost.')}
 }
 function stopCamera(update=true){cancelAnimationFrame(rafRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;if(update){setCameraOn(false);setVisionReady(false);setContinuous(false)}}
 function switchCamera(){if(devices.length<2)return;const i=Math.max(0,devices.findIndex(d=>d.deviceId===deviceId));const id=devices[(i+1)%devices.length].deviceId;setDeviceId(id);void startCamera(id)}

 function loop(){const tick=(now:number)=>{const v=videoRef.current,c=overlayRef.current;if(v&&c&&v.readyState>=2){if(c.width!==v.videoWidth||c.height!==v.videoHeight){c.width=v.videoWidth;c.height=v.videoHeight}const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);let f=lastVisionRef.current;if(visionReadyRef.current&&now-lastDetectRef.current>70){const dt=now-lastDetectRef.current;lastDetectRef.current=now;setFps(Math.round(1000/Math.max(dt,1)));try{f=detectFrame(v,modeRef.current as VisionMode,now);lastVisionRef.current=f}catch(e){console.error(e)}}drawOverlay(ctx,c,f,modeRef.current,objectLockRef.current,humanProfileRef.current);if(modeRef.current==='human'||modeRef.current==='mocap'){updateHumanRegions(f);if(modeRef.current==='human'&&humanAutoRef.current)void maybeAutoHumanFrame(now,f)}if(modeRef.current==='object'&&continuousRef.current)void maybeAutoKeyframe(now,f)}rafRef.current=requestAnimationFrame(tick)};rafRef.current=requestAnimationFrame(tick)}

 async function enableOrientation(){try{const D=DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<'granted'|'denied'>};if(D.requestPermission&&await D.requestPermission()!=='granted')throw new Error();const handler=(e:DeviceOrientationEvent)=>{if(typeof e.alpha==='number')orientationRef.current=e.alpha};window.addEventListener('deviceorientation',handler,{passive:true});setOrientationEnabled(true);setMessage('Đã bật cảm biến hướng. Coverage 360° sẽ chính xác hơn.')}catch{setOrientationEnabled(false);setMessage('Không dùng được cảm biến hướng; app sẽ fallback theo nhịp quay đều.')}}

 function lockBestObject(){const list=lastVisionRef.current.objects||[];const best=[...list].sort((a,b)=>b.score-a.score)[0];if(best){objectLockRef.current=best.box;setObjectLock(best.box);setObjectLabel(`${best.label} ${Math.round(best.score*100)}%`);setMessage('Đã khóa vật thể. Giữ vật ở giữa và đi vòng quanh.')}else{const v=videoRef.current;if(!v?.videoWidth)return;const b={x:v.videoWidth*.17,y:v.videoHeight*.12,width:v.videoWidth*.66,height:v.videoHeight*.76};objectLockRef.current=b;setObjectLock(b);setObjectLabel('Vùng quét thủ công');setMessage('Không nhận diện được tên vật thể; đã khóa vùng giữa để vẫn quét được vật bất kỳ.')}}
 function selectObjectAt(e:React.PointerEvent<HTMLCanvasElement>){if(mode!=='object')return;const c=overlayRef.current;if(!c)return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*c.width,y=(e.clientY-r.top)/r.height*c.height;const hit=(lastVisionRef.current.objects||[]).filter(o=>x>=o.box.x&&x<=o.box.x+o.box.width&&y>=o.box.y&&y<=o.box.y+o.box.height).sort((a,b)=>b.score-a.score)[0];if(hit){objectLockRef.current=hit.box;setObjectLock(hit.box);setObjectLabel(`${hit.label} ${Math.round(hit.score*100)}%`);setMessage('Đã khóa vật thể bạn chạm vào.')}}

 function startContinuous(){if(!cameraOn){void startCamera();return}if(!objectLockRef.current)lockBestObject();if(!orientationEnabled)void enableOrientation();keyframesRef.current.forEach(k=>k.previewUrl&&URL.revokeObjectURL(k.previewUrl));setKeyframes([]);keyframesRef.current=[];const emptyCoverage=Array(8).fill(false) as boolean[];setCoverage(emptyCoverage);coverageRef.current=emptyCoverage;setMesh(null);lastAngleRef.current=null;lastCaptureTsRef.current=0;setContinuous(true);continuousRef.current=true;setMessage('Đang quét liên tục: đi chậm một vòng quanh vật thể, giữ khoảng cách tương đối ổn định.')}
 function stopContinuous(){setContinuous(false);continuousRef.current=false;setMessage(`Đã dừng. Có ${keyframesRef.current.length} keyframe. ${keyframesRef.current.length>=12?'Có thể dựng 3D.':'Nên quét thêm góc.'}`)}

 async function maybeAutoKeyframe(now:number,f:VisionFrame){
  if(captureBusyRef.current||now-lastCaptureTsRef.current<520||keyframesRef.current.length>=36)return;const v=videoRef.current;if(!v?.videoWidth)return;
  const q=analyzeVideo(v,f);setScanQuality(q);if(q.brightness<18||q.brightness>92||q.sharpness<28)return;
  let angle=orientationRef.current;let source:'orientation'|'timed'='orientation';if(angle===null){source='timed';angle=(keyframesRef.current.length*15)%360}else if(lastAngleRef.current!==null&&angularDistance(angle,lastAngleRef.current)<9)return;
  captureBusyRef.current=true;try{const seg=makeObjectMask(v,objectLockRef.current);setScanQuality({...q,mask:Math.round(seg.confidence*100)});if(seg.confidence<.22)return;const blob=await canvasBlob(seg.previewCanvas,'image/jpeg',.76);const url=URL.createObjectURL(blob);const k:ObjectKeyframe={id:globalThis.crypto?.randomUUID?.()??`${Date.now()}`,angleDeg:angle,createdAt:new Date().toISOString(),width:seg.width,height:seg.height,aspect:seg.aspect,mask:seg.mask,foregroundRatio:seg.foregroundRatio,confidence:seg.confidence,source,previewUrl:url};const next=[...keyframesRef.current,k];setKeyframes(next);keyframesRef.current=next;lastAngleRef.current=angle;lastCaptureTsRef.current=now;const sec=Math.round((((angle%360)+360)%360)/45)%8;setCoverage(prev=>{const nextCov=prev.map((v,i)=>i===sec?true:v);coverageRef.current=nextCov;return nextCov});peerRef.current?.send({type:'capture',payload:{sector:sec,angle,quality:q}});if(next.length>=16&&coverageRef.current.filter(Boolean).length>=6)setMessage('Đã có nhiều góc tốt. Có thể tiếp tục đủ 360° hoặc dừng để dựng thử 3D.');}finally{captureBusyRef.current=false}
 }

 async function manualFrame(){const v=videoRef.current;if(!v?.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')!.drawImage(v,0,0);const blob=await canvasBlob(c,'image/jpeg',.88);const q=analyzeVideo(v,lastVisionRef.current);const now=new Date().toISOString();await saveFrame({id:globalThis.crypto?.randomUUID?.()??`frame-${Date.now()}-${Math.random()}`,projectId:projectId.current,createdAt:now,mode,width:c.width,height:c.height,brightness:q.brightness/100,blurScore:q.sharpness,trackingScore:q.tracking,orientationDeg:orientationRef.current,coverageSector:null,size:blob.size,blob,deviceId:localDeviceId.current,sessionId:sessionCode,cameraSettings:streamRef.current?.getVideoTracks()[0]?.getSettings() as unknown as Record<string,unknown>});const meta=await listFrameMeta(projectId.current);setStoredFrames(meta.length);setStoredBytes(await estimateStoredBytes(projectId.current));await saveProject({id:projectId.current,version:6,mode,createdAt:createdAt.current,updatedAt:now,frameCount:meta.length,sessionId:sessionCode,scanState:'scanning'});setMessage('Đã lưu frame gốc vào IndexedDB.')}

 async function build3d(){if(keyframes.length<6){setMessage('Cần ít nhất 6 góc; khuyến nghị 16–24 keyframe quanh vật thể.');return}setBuilding(true);setContinuous(false);continuousRef.current=false;setMessage('Đang voxel carving để tạo mesh 3D thật…');await new Promise(r=>setTimeout(r,60));try{const mm=Math.max(10,Number(widthMm)||300);const m=reconstructVisualHull(keyframes,voxelRes,mm/1000);setMesh(m);setMessage(`Đã dựng mesh Visual Hull: ${m.occupied.toLocaleString()} voxel, ${(m.indices.length/3).toLocaleString()} mặt tam giác.`)}catch(e){setMessage(e instanceof Error?e.message:'Dựng 3D thất bại.')}finally{setBuilding(false)}}
 async function exportMesh(kind:'glb'|'obj'|'ply'){if(!mesh)return;const base=`scan-object-${new Date().toISOString().slice(0,19).replaceAll(':','-')}`;if(kind==='obj')downloadBlob(meshToObj(mesh),`${base}.obj`);if(kind==='ply')downloadBlob(meshToPly(mesh),`${base}.ply`);if(kind==='glb'){setMessage('Đang đóng gói GLB…');try{downloadBlob(await meshToGlb(mesh),`${base}.glb`);setMessage('Đã xuất GLB.')}catch(e){setMessage(e instanceof Error?e.message:'Không xuất được GLB.')}}}

 function updateHumanRegions(f:VisionFrame){setHumanRegions(calcHumanRegions(f))}
 async function maybeAutoHumanFrame(now:number,f:VisionFrame){if(humanCaptureBusyRef.current||now-humanLastTsRef.current<650)return;const v=videoRef.current;if(!v?.videoWidth)return;const regions=calcHumanRegions(f),score=scoreHumanProfile(regions,humanProfileRef.current),q=analyzeVideo(v,f);if(score<68||q.sharpness<28||q.brightness<18||q.brightness>92)return;let angle=orientationRef.current;if(angle!==null&&humanLastAngleRef.current!==null&&angularDistance(angle,humanLastAngleRef.current)<10)return;humanCaptureBusyRef.current=true;try{const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')!.drawImage(v,0,0);const blob=await canvasBlob(c,'image/jpeg',.8);const t=new Date().toISOString();await saveFrame({id:globalThis.crypto?.randomUUID?.()??`human-${Date.now()}-${Math.random()}`,projectId:projectId.current,createdAt:t,mode:'human',width:c.width,height:c.height,brightness:q.brightness/100,blurScore:q.sharpness,trackingScore:score,orientationDeg:angle,coverageSector:angle===null?null:Math.round((((angle%360)+360)%360)/45)%8,size:blob.size,blob,deviceId:localDeviceId.current,sessionId:sessionCode,cameraSettings:streamRef.current?.getVideoTracks()[0]?.getSettings() as unknown as Record<string,unknown>});humanLastTsRef.current=now;humanLastAngleRef.current=angle;setHumanKeyframes(x=>x+1)}finally{humanCaptureBusyRef.current=false}}
 function startHumanAuto(){if(!cameraOn){void startCamera();return}if(!orientationEnabled)void enableOrientation();setHumanKeyframes(0);humanLastTsRef.current=0;humanLastAngleRef.current=null;setHumanAuto(true);setMessage(`Đang quét liên tục ${humanProfile==='full'?'toàn thân':humanProfile==='upper'?'nửa người trên':humanProfile==='head'?'đầu & vai':'khuôn mặt'}; app tự giữ frame đạt chất lượng.`)}
 function stopHumanAuto(){setHumanAuto(false);setMessage(`Đã dừng quét người. Đã giữ ${humanKeyframes} keyframe đạt yêu cầu.`)}

 async function createHost(){peerRef.current?.close();const p=new ManualPeer();peerRef.current=p;p.onState=s=>setPeerState(s);p.onMessage=m=>{if(m.type==='capture')setMessage('Máy phụ vừa gửi trạng thái capture.')};setSignalOut(await p.createOffer());setPeerState('Đã tạo Offer • gửi chuỗi này cho máy Join')}
 async function acceptOffer(){peerRef.current?.close();const p=new ManualPeer();peerRef.current=p;p.onState=s=>setPeerState(s);setSignalOut(await p.acceptOffer(signalIn));setPeerState('Đã tạo Answer • gửi lại cho Host')}
 async function acceptAnswer(){await peerRef.current?.acceptAnswer(signalIn);setPeerState('Đang hoàn tất kết nối…')}

 const coveragePct=Math.round(coverage.filter(Boolean).length/8*100),modeInfo=useMemo(()=>modes.find(m=>m.id===mode)!,[mode]);
 const humanNeed=humanProfile==='head'?['face']:humanProfile==='upper'?['face','torso','leftArm','rightArm','hands']:humanProfile==='face'?['face']:['face','torso','leftArm','rightArm','legs','hands'];
 const humanScore=Math.round(humanNeed.reduce((s,k)=>s+humanRegions[k as keyof typeof humanRegions],0)/humanNeed.length);

 return <main>
  <header className="appHeader"><div className="brand"><div className="brandMark">◈</div><div><b>3D Scanner Studio</b><span>Mobile Reconstruction Workspace</span></div></div><div className="headerMeta"><span className={cameraOn?'live':'idle'}>{cameraOn?'● LIVE':'● READY'}</span><i>{secure?'HTTPS':'HTTP'}</i><i>{videoSize}</i></div></header>
  <nav className="modes">{modes.map(m=><button key={m.id} className={mode===m.id?'active':''} onClick={()=>setMode(m.id)}><span className="modeIcon">{m.icon}</span><span><b>{m.title}</b><small>{m.sub}</small></span></button>)}</nav>

  <section className="heroBar"><div><span className="eyebrow">{mode==='object'?'OBJECT RECONSTRUCTION':mode==='human'?'HUMAN CAPTURE':mode==='room'?'SITE CAPTURE':'MOTION TRACKING'}</span><h1>{modeInfo.title}</h1><p>{mode==='object'?'Quay liên tục. App tự chọn keyframe, tách silhouette và dựng Visual Hull 3D ngay trên máy.':mode==='human'?'Không bắt buộc toàn thân: chọn phạm vi theo mục đích rồi tracking đúng vùng cần thiết.':mode==='room'?'Thu hiện trạng theo coverage; reconstruction kiến trúc sẽ dùng depth/camera pose ở bước kế tiếp.':'Theo dõi pose, mặt và bàn tay để ghi chuyển động.'}</p></div><div className="heroActions"><button onClick={()=>cameraOn?stopCamera():void startCamera()}>{cameraOn?'Dừng camera':'Bật camera'}</button><button onClick={switchCamera} disabled={devices.length<2}>Đổi camera</button></div></section>

  <section className="work">
   <div className="cameraCard"><div className="cameraTop"><span>{cameraOn?'CAMERA ACTIVE':'CAMERA OFF'}</span><span>{fps?`${fps} FPS`:'— FPS'}</span><span>{mode==='object'&&continuous?'AUTO CAPTURE':'MANUAL'}</span></div><video ref={videoRef} playsInline muted/><canvas ref={overlayRef} onPointerDown={selectObjectAt}/>{!cameraOn&&<div className="emptyState"><div className="orb">◈</div><b>Camera chưa bật</b><span>Ưu tiên camera sau trên điện thoại</span></div>}<div className="cameraHint">{message}</div></div>

   <aside className="controlPanel">
    <div className="panelTitle"><div><span className="eyebrow">SCAN CONTROL</span><h2>{modeInfo.title}</h2></div><span className={visionReady||mode==='room'?'statusGood':'statusWait'}>{visionReady||mode==='room'?'READY':'AI…'}</span></div>
    <label className="field"><span>Camera</span><select value={deviceId} onChange={e=>{setDeviceId(e.target.value);if(cameraOn)void startCamera(e.target.value)}}><option value="">Camera sau / mặc định</option>{devices.map((d,i)=><option key={d.deviceId} value={d.deviceId}>{d.label||`Camera ${i+1}`}</option>)}</select></label>
    <label className="field"><span>Độ phân giải</span><select value={resolution} onChange={e=>setResolution(e.target.value)}><option>1280x720</option><option>1920x1080</option><option>2560x1440</option></select></label>
    {mode==='object'?<ObjectControls/>:mode==='human'?<HumanControls/>:<GenericControls/>}
    <div className="storageLine"><span>Frame gốc</span><b>{storedFrames}</b><span>Dung lượng</span><b>{formatBytes(storedBytes)}</b></div>
   </aside>
  </section>

  {mode==='object'&&<>
   <section className="pipelinePanel"><div className="sectionHead"><div><span className="eyebrow">REAL 3D PIPELINE</span><h3>Quay → Keyframe → Silhouette → Voxel → Mesh → Export</h3></div><span className="foundation">Visual Hull v1</span></div><div className="steps"><Step n="1" title="Khóa vật" ok={!!objectLock}/><Step n="2" title="Quét liên tục" ok={keyframes.length>=8}/><Step n="3" title="Coverage" ok={coveragePct>=75}/><Step n="4" title="Dựng mesh" ok={!!mesh}/><Step n="5" title="GLB / OBJ / PLY" ok={!!mesh}/></div></section>
   <section className="reconGrid"><div className="keyPanel"><div className="sectionHead"><div><h3>Keyframe tự động</h3><p>Chỉ giữ frame đủ nét và góc mới. Khuyến nghị 16–24 frame.</p></div><strong>{keyframes.length}/36</strong></div><div className="coverageRing"><div className="ring" style={{'--p':`${coveragePct*3.6}deg`} as React.CSSProperties}><b>{coveragePct}%</b><span>360°</span></div><div className="sectors">{coverage.map((v,i)=><div key={i} className={v?'done':''}><b>{i+1}</b><span>{sectorNames[i]}</span></div>)}</div></div><div className="thumbGrid">{keyframes.slice(-12).map((k,i)=><div key={k.id}><img src={k.previewUrl}/><span>{Math.round(k.angleDeg)}°</span><i>{Math.round(k.confidence*100)}%</i></div>)}{!keyframes.length&&<p className="muted">Chưa có keyframe. Bấm “Quét liên tục” rồi đi một vòng quanh vật thể.</p>}</div></div>
    <div className="qualityPanel"><div className="sectionHead"><div><h3>Chất lượng đầu vào</h3><p>App bỏ frame rung/mờ trước khi reconstruction.</p></div></div><Metric label="Ánh sáng" value={scanQuality.brightness}/><Metric label="Độ nét" value={scanQuality.sharpness}/><Metric label="Tracking" value={scanQuality.tracking}/><Metric label="Silhouette" value={scanQuality.mask}/><div className="logicNote"><b>Quan trọng</b><p>Visual Hull tạo hình khối thật từ silhouette nhiều góc. Bề mặt lõm sâu và texture photogrammetry sẽ cần SfM/MVS ở phiên bản sau.</p></div></div>
   </section>
   <section className="meshPanel"><div className="meshPreview"><canvas ref={previewRef}/>{!mesh&&<div className="previewEmpty"><b>3D Preview</b><span>Dựng mesh xong sẽ xem và xoay trực tiếp ở đây.</span></div>}</div><div className="meshInfo"><span className="eyebrow">RECONSTRUCTION OUTPUT</span><h3>{mesh?'Mesh 3D đã tạo':'Chưa có mesh'}</h3>{mesh?<><div className="meshStats"><div><b>{mesh.occupied.toLocaleString()}</b><span>Voxel</span></div><div><b>{(mesh.indices.length/3).toLocaleString()}</b><span>Triangles</span></div><div><b>{Math.round(mesh.bounds.width*1000)}</b><span>mm width</span></div></div><p>GLB dùng mét, OBJ/PLY giữ cùng scale. Model hiện là geometry thật, chưa texture.</p><div className="exportBtns"><button onClick={()=>void exportMesh('glb')}>Xuất GLB</button><button onClick={()=>void exportMesh('obj')}>Xuất OBJ</button><button onClick={()=>void exportMesh('ply')}>Xuất PLY</button></div></>:<p>Quét đủ vòng rồi bấm “Dựng 3D”.</p>}</div></section>
  </>}

  {mode==='human'&&<section className="humanPanel"><div className="sectionHead"><div><span className="eyebrow">HUMAN PROFILE</span><h3>Chọn đúng phạm vi — không bắt buộc quét toàn thân</h3></div><strong>{humanScore}%</strong></div><div className="profileCards">{([{id:'head',t:'Đầu & vai',s:'Avatar nhanh'}, {id:'upper',t:'Nửa người trên',s:'Game / avatar'}, {id:'full',t:'Toàn thân',s:'Character rig'}, {id:'face',t:'Face Detail',s:'Mesh / face rig'}] as {id:HumanProfile;t:string;s:string}[]).map(p=><button key={p.id} className={humanProfile===p.id?'active':''} onClick={()=>setHumanProfile(p.id)}><b>{p.t}</b><span>{p.s}</span></button>)}</div><div className="bodyMetrics"><Metric label="Face" value={humanRegions.face}/><Metric label="Torso" value={humanRegions.torso}/><Metric label="Tay trái" value={humanRegions.leftArm}/><Metric label="Tay phải" value={humanRegions.rightArm}/><Metric label="Chân" value={humanRegions.legs}/><Metric label="Bàn tay" value={humanRegions.hands}/></div><p className="logicNote"><b>Đích cuối:</b> silhouette + multi-view/depth → body mesh → retopology → humanoid rig → skin weight → animation-ready. Skeleton trên camera chỉ là tracking, không dùng thay hình khối cơ thể.</p></section>}

  <section className="systemPanel"><div className="sectionHead"><div><span className="eyebrow">DEVICE FOUNDATION</span><h3>Thiết bị & Multi-device</h3></div><button onClick={()=>setMultiOpen(v=>!v)}>{multiOpen?'Thu gọn':'Mở Multi-device'}</button></div><div className="chips"><span className={secure?'ok':'bad'}>HTTPS {secure?'✓':'✕'}</span><span className={webgl?'ok':'bad'}>WebGL {webgl?'✓':'✕'}</span><span className={webgpu?'ok':'warn'}>WebGPU {webgpu?'✓':'—'}</span><span className={webxr?'ok':'warn'}>WebXR {webxr?'✓':'—'}</span><span className={idbOk?'ok':'bad'}>IndexedDB {idbOk?'✓':'✕'}</span><span className={orientationEnabled?'ok':'warn'}>Orientation {orientationEnabled?'✓':'—'}</span></div>{multiOpen&&<div className="multi"><div className="multiTop"><label>Vai trò<select value={role} onChange={e=>setRole(e.target.value as DeviceRole)}><option value="auto">Auto</option><option value="front">Front</option><option value="back">Back</option><option value="left">Left</option><option value="right">Right</option><option value="top">Top</option></select></label><div><b>Session {sessionCode}</b><span>{peerState}</span></div></div><div className="pairBtns"><button onClick={()=>void createHost()}>Tạo Host Offer</button><button onClick={()=>void acceptOffer()}>Nhận Offer → Answer</button><button onClick={()=>void acceptAnswer()}>Host nhận Answer</button></div><div className="signal"><textarea value={signalIn} onChange={e=>setSignalIn(e.target.value)} placeholder="Dán Offer/Answer từ máy kia"/><textarea value={signalOut} readOnly placeholder="Chuỗi tạo ra sẽ hiện ở đây"/></div><p>v0.6 vẫn giữ P2P trạng thái. Truyền ảnh lớn giữa nhiều máy cần chunking/checksum/retry trước khi bật mặc định.</p></div>}</section>
  <footer><span>3D Scanner Studio v0.6</span><span>Local-first • Không tự upload dữ liệu scan</span></footer>
 </main>

 function ObjectControls(){return <div className="objectControls"><div className="lockRow"><button onClick={lockBestObject} disabled={!cameraOn}>⌖ Khóa vật thể</button><span>{objectLabel}</span></div><div className="primaryRow"><button className={continuous?'danger':'primary'} onClick={continuous?stopContinuous:startContinuous}>{continuous?'■ Dừng quét':'● Quét liên tục'}</button><button onClick={()=>void manualFrame()} disabled={!cameraOn}>Chụp frame</button></div><div className="inlineFields"><label><span>Rộng thực (mm)</span><input value={widthMm} inputMode="decimal" onChange={e=>setWidthMm(e.target.value)}/></label><label><span>Voxel</span><select value={voxelRes} onChange={e=>setVoxelRes(Number(e.target.value))}><option value={32}>32 nhẹ</option><option value={42}>42 chuẩn</option><option value={52}>52 nét hơn</option></select></label></div><button className="buildBtn" onClick={()=>void build3d()} disabled={building||keyframes.length<6}>{building?'Đang dựng…':`Dựng 3D từ ${keyframes.length} keyframe`}</button></div>}
 function HumanControls(){return <div className="humanControls"><label className="field"><span>Phạm vi quét người</span><select value={humanProfile} onChange={e=>setHumanProfile(e.target.value as HumanProfile)}><option value="head">Đầu & vai</option><option value="upper">Nửa người trên</option><option value="full">Toàn thân</option><option value="face">Face Detail</option></select></label><div className="humanScore"><b>{humanScore}%</b><span>Tracking đúng vùng yêu cầu • {humanKeyframes} keyframe</span></div><div className="primaryRow"><button className={humanAuto?'danger':'primary'} onClick={humanAuto?stopHumanAuto:startHumanAuto}>{humanAuto?'■ Dừng quét':'● Quét liên tục'}</button><button onClick={()=>void manualFrame()} disabled={!cameraOn}>Chụp tay</button></div></div>}
 function GenericControls(){return <div className="generic"><button className="primary" onClick={()=>void manualFrame()} disabled={!cameraOn}>Lưu frame hiện trạng</button><p>Room reconstruction thật cần camera pose/depth fusion. Bản này giữ phần thu dữ liệu, coverage và multi-device để không giả mesh kiến trúc.</p></div>}
}

function Step({n,title,ok}:{n:string;title:string;ok:boolean}){return <div className={ok?'done':''}><b>{ok?'✓':n}</b><span>{title}</span></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><div><span>{label}</span><b>{Math.round(value)}%</b></div><i><em style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></i></div>}
function formatBytes(n:number){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function canvasBlob(c:HTMLCanvasElement,type='image/jpeg',quality=.85){return new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Không tạo được ảnh')),type,quality))}
function analyzeVideo(v:HTMLVideoElement,f:VisionFrame){const c=document.createElement('canvas');c.width=64;c.height=64;const x=c.getContext('2d',{willReadFrequently:true})!;x.drawImage(v,0,0,64,64);const d=x.getImageData(0,0,64,64).data,g=new Float32Array(4096);let sum=0;for(let i=0,p=0;i<d.length;i+=4,p++){const q=(d[i]*.299+d[i+1]*.587+d[i+2]*.114)/255;g[p]=q;sum+=q}let ss=0,s=0,n=0;for(let y=1;y<63;y++)for(let xx=1;xx<63;xx++){const i=y*64+xx,l=4*g[i]-g[i-1]-g[i+1]-g[i-64]-g[i+64];s+=l;ss+=l*l;n++}const variance=Math.max(0,ss/n-(s/n)**2);const brightness=Math.round(sum/g.length*100),sharpness=Math.max(0,Math.min(100,Math.round(variance*5000)));const tracking=f.objects?.length?Math.min(100,Math.round(Math.max(...f.objects.map(o=>o.score))*100)):0;return{brightness,sharpness,tracking,mask:0}}
function calcHumanRegions(f:VisionFrame){const p=f.pose?.[0]||[],face=f.face?.[0]||[],hands=f.hands||[];const vis=(ids:number[])=>Math.round(ids.filter(i=>p[i]&&(p[i].visibility??1)>.45).length/ids.length*100);return{face:face.length?100:vis([0,1,2,3,4,5,6,7,8,9,10]),torso:vis([11,12,23,24]),leftArm:vis([11,13,15]),rightArm:vis([12,14,16]),legs:vis([23,24,25,26,27,28,29,30,31,32]),hands:Math.round(Math.min(1,hands.length/2)*100)}}
function scoreHumanProfile(r:ReturnType<typeof calcHumanRegions>,p:HumanProfile){const keys=p==='head'?['face'] as const:p==='face'?['face'] as const:p==='upper'?['face','torso','leftArm','rightArm','hands'] as const:['face','torso','leftArm','rightArm','legs','hands'] as const;return Math.round(keys.reduce((s,k)=>s+r[k],0)/keys.length)}
function drawOverlay(ctx:CanvasRenderingContext2D,c:HTMLCanvasElement,f:VisionFrame,mode:Mode,lock:ObjectBox|null,profile:HumanProfile){ctx.save();ctx.lineWidth=Math.max(2,c.width/500);if(mode==='object'){ctx.strokeStyle='rgba(126,145,255,.75)';ctx.setLineDash([12,10]);ctx.strokeRect(c.width*.13,c.height*.12,c.width*.74,c.height*.76);ctx.setLineDash([]);for(const ob of f.objects||[]){ctx.strokeStyle='rgba(255,201,78,.8)';ctx.strokeRect(ob.box.x,ob.box.y,ob.box.width,ob.box.height)}if(lock){ctx.strokeStyle='#4ade80';ctx.lineWidth=Math.max(3,c.width/350);ctx.strokeRect(lock.x,lock.y,lock.width,lock.height);ctx.fillStyle='rgba(74,222,128,.12)';ctx.fillRect(lock.x,lock.y,lock.width,lock.height)}}else if(mode==='human'||mode==='mocap'){const lm=f.pose?.[0]||[];ctx.strokeStyle='#4ade80';ctx.fillStyle='#4ade80';for(const[a,b]of POSE_CONNECTIONS)if(lm[a]&&lm[b]){ctx.beginPath();ctx.moveTo(lm[a].x*c.width,lm[a].y*c.height);ctx.lineTo(lm[b].x*c.width,lm[b].y*c.height);ctx.stroke()}for(const p of lm){if((p.visibility??1)<.35)continue;ctx.beginPath();ctx.arc(p.x*c.width,p.y*c.height,2.8,0,Math.PI*2);ctx.fill()}ctx.fillStyle='rgba(68,186,255,.72)';for(const face of f.face||[])for(let i=0;i<face.length;i+=3){const p=face[i];ctx.fillRect(p.x*c.width,p.y*c.height,1.4,1.4)}ctx.strokeStyle='#ffd34f';ctx.fillStyle='#ffd34f';for(const hand of f.hands||[]){for(const[a,b]of HAND_CONNECTIONS)if(hand[a]&&hand[b]){ctx.beginPath();ctx.moveTo(hand[a].x*c.width,hand[a].y*c.height);ctx.lineTo(hand[b].x*c.width,hand[b].y*c.height);ctx.stroke()}for(const p of hand){ctx.beginPath();ctx.arc(p.x*c.width,p.y*c.height,2,0,Math.PI*2);ctx.fill()}}ctx.strokeStyle='rgba(255,255,255,.45)';ctx.setLineDash([10,8]);if(profile==='face'){ctx.beginPath();ctx.ellipse(c.width/2,c.height*.38,c.width*.19,c.height*.24,0,0,Math.PI*2);ctx.stroke()}else if(profile==='head'){ctx.strokeRect(c.width*.24,c.height*.12,c.width*.52,c.height*.52)}else if(profile==='upper'){ctx.strokeRect(c.width*.18,c.height*.09,c.width*.64,c.height*.72)}else ctx.strokeRect(c.width*.25,c.height*.04,c.width*.5,c.height*.92)}else{ctx.strokeStyle='rgba(255,255,255,.45)';ctx.setLineDash([12,10]);ctx.strokeRect(c.width*.08,c.height*.08,c.width*.84,c.height*.84)}ctx.restore()}

createRoot(document.getElementById('root')!).render(<App/>);
