export type StoredFrameMeta={id:string;projectId:string;createdAt:string;mode:string;width:number;height:number;brightness:number;blurScore:number;trackingScore:number;orientationDeg:number|null;coverageSector:number|null;size:number;deviceId?:string;sessionId?:string;cameraSettings?:Record<string,unknown>};
type StoredFrame=StoredFrameMeta&{blob:Blob};
export type ProjectMeta={id:string;version:number;mode:string;createdAt:string;updatedAt:string;frameCount:number;sessionId?:string;scanState?:string};
export type SessionMeta={id:string;version:number;code:string;createdAt:string;updatedAt:string;scanState:string;hostDeviceId:string;calibration?:{type:string;referenceMm:number|null;notes:string};devices?:Array<Record<string,unknown>>};
const DB_NAME='scanner-studio-db',DB_VERSION=2,FRAME_STORE='frames',PROJECT_STORE='projects',SESSION_STORE='sessions';
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(FRAME_STORE)){const frames=db.createObjectStore(FRAME_STORE,{keyPath:'id'});frames.createIndex('projectId','projectId',{unique:false});frames.createIndex('createdAt','createdAt',{unique:false})}if(!db.objectStoreNames.contains(PROJECT_STORE))db.createObjectStore(PROJECT_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(SESSION_STORE))db.createObjectStore(SESSION_STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error??new Error('Không mở được IndexedDB'))})}
function txDone(tx:IDBTransaction):Promise<void>{return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error??new Error('IndexedDB transaction failed'));tx.onabort=()=>reject(tx.error??new Error('IndexedDB transaction aborted'))})}
export async function testIndexedDb(){if(!('indexedDB'in window))return false;try{const db=await openDb();db.close();return true}catch{return false}}
export async function saveFrame(frame:StoredFrame){const db=await openDb(),tx=db.transaction([FRAME_STORE],'readwrite');tx.objectStore(FRAME_STORE).put(frame);await txDone(tx);db.close()}
export async function saveProject(project:ProjectMeta){const db=await openDb(),tx=db.transaction([PROJECT_STORE],'readwrite');tx.objectStore(PROJECT_STORE).put(project);await txDone(tx);db.close()}
export async function saveSession(session:SessionMeta){const db=await openDb(),tx=db.transaction([SESSION_STORE],'readwrite');tx.objectStore(SESSION_STORE).put(session);await txDone(tx);db.close()}
export async function loadLatestSession():Promise<SessionMeta|null>{const db=await openDb(),tx=db.transaction([SESSION_STORE],'readonly'),req=tx.objectStore(SESSION_STORE).getAll();const rows=await new Promise<SessionMeta[]>((resolve,reject)=>{req.onsuccess=()=>resolve(req.result as SessionMeta[]);req.onerror=()=>reject(req.error)});await txDone(tx);db.close();return rows.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0]??null}
export async function listFrameMeta(projectId:string):Promise<StoredFrameMeta[]>{const db=await openDb(),tx=db.transaction([FRAME_STORE],'readonly'),index=tx.objectStore(FRAME_STORE).index('projectId'),request=index.getAll(IDBKeyRange.only(projectId));const rows=await new Promise<StoredFrame[]>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result as StoredFrame[]);request.onerror=()=>reject(request.error??new Error('Không đọc được frame'))});await txDone(tx);db.close();return rows.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(({blob:_blob,...meta})=>meta)}
export async function getRecentFrameUrls(projectId:string,mode?:string,limit=6){const db=await openDb(),tx=db.transaction([FRAME_STORE],'readonly'),index=tx.objectStore(FRAME_STORE).index('projectId'),request=index.getAll(IDBKeyRange.only(projectId));const rows=await new Promise<StoredFrame[]>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result as StoredFrame[]);request.onerror=()=>reject(request.error??new Error('Không đọc được thumbnail'))});await txDone(tx);db.close();return rows.filter(r=>!mode||r.mode===mode).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,limit).reverse().map(r=>URL.createObjectURL(r.blob))}
export async function clearProject(projectId:string){const db=await openDb(),tx=db.transaction([FRAME_STORE,PROJECT_STORE],'readwrite'),frameStore=tx.objectStore(FRAME_STORE),index=frameStore.index('projectId'),request=index.openCursor(IDBKeyRange.only(projectId));request.onsuccess=()=>{const cursor=request.result;if(!cursor)return;cursor.delete();cursor.continue()};tx.objectStore(PROJECT_STORE).delete(projectId);await txDone(tx);db.close()}
export async function estimateStoredBytes(projectId:string){return(await listFrameMeta(projectId)).reduce((s,f)=>s+f.size,0)}
